package test;

import static org.junit.Assert.assertEquals;

import org.junit.BeforeClass;
import org.junit.Test;

import exceptions.DepartmentNotFoundException;
import exceptions.MineNotFoundException;
import models.Colombia;
import models.Department;
import models.DepartmentName;
import models.Mine;
import models.MineType;
import models.OreType;

public class ModelTest {
	static Department depart;
	static Colombia country;

	@BeforeClass
	public static void generateData() throws MineNotFoundException {
		country = new Colombia();
		depart = new Department(DepartmentName.ANTIOQUIA, 250000);
	}

	@Test
	public void whenSearchMine_thenok() throws MineNotFoundException {

		int id = 0;
		Mine testMine = new Mine("minaDePrueba", 150, OreType.COBRE, 1200, id, MineType.SUBTERRANEAN_MINE, 20000);
		depart.addMine(testMine);
		int mine = depart.searchPositionMine(id);
		assertEquals(id, mine);
	}

	@Test(expected = MineNotFoundException.class)
	public void whenRemoveMine_thenFail() throws MineNotFoundException {
		assertEquals(MineNotFoundException.class, depart.removeMine(10));
	}
	
	
  
	@Test
	public void whenSearchMineTwo_thenOk() throws MineNotFoundException {
		int id = depart.getListMine().size() + 1;
		Mine testMine = new Mine("minaDePrueba", 150, OreType.COBRE, 1200, id, MineType.SUBTERRANEAN_MINE, 20000);
		depart.addMine(testMine);
		assertEquals("minaDePrueba", depart.searchMine(id).getName());
	}
	
	@Test
	public void whenSellOre_thenOk() throws MineNotFoundException {
		depart.addMine(new Mine("Nombre", 250, OreType.GOLD, 9000, 45, MineType.SUBTERRANEAN_MINE, 1500000));
		depart.sellOre(45, 50);
	}
	
	@Test(expected = MineNotFoundException.class)
	public void whenSellOre_thenFail() throws MineNotFoundException {
		depart.addMine(new Mine("Nombre", 250, OreType.GOLD, 9000, 45, MineType.SUBTERRANEAN_MINE, 1500000));
		depart.sellOre(depart.getListMine().size() - 1, 50);
	}
	
	
	
	@Test
	public void  whenCreateMine_thenOk() throws DepartmentNotFoundException, MineNotFoundException {
		country.autogenerateDepartment();
		country.createMine(DepartmentName.ANTIOQUIA, "YO-No-se", 1500, OreType.COAL, 1900, MineType.SUBTERRANEAN_MINE, 5520);
	}
	
	
	@Test
	public void whenRemoveMine_thenOk() throws MineNotFoundException {
		depart.removeMine(0);
	}
	
	@Test
	public void whenSearchMine_thenOK() throws MineNotFoundException{
		Mine mineTest = new Mine("Nombre", 500,OreType.COAL, 1500, 15, MineType.SUBTERRANEAN_MINE, 150000);
		depart.addMine(mineTest);
		int id = 15;
		Mine mine = depart.searchMine(id);
		assertEquals(mineTest, mine);
	}
	
	@Test(expected=MineNotFoundException.class)
	public void whenSearchMine_thenFail() throws MineNotFoundException {
		Mine mineTest = new Mine("Nombre", 500,OreType.COAL, 1500, 15, MineType.SUBTERRANEAN_MINE, 150000);
		depart.addMine(mineTest);
		int id = 20;
		Mine mine = depart.searchMine(id);
		assertEquals(mineTest, mine);
	}
	
	@Test(expected=MineNotFoundException.class)
	public void whenCreateMine_thenFail() throws DepartmentNotFoundException, MineNotFoundException {
		Department departTest = new Department(DepartmentName.ANTIOQUIA, 150000);
		departTest.addMine(new Mine("Nombre", 1500, OreType.AGREGADOS, 1500, 15, MineType.OPEN_PIT_MINE, 150000));
	}
	
	
}
