package controllers;
import views.IOManager;
import exceptions.DepartmentNotFoundException;
import exceptions.MineNotFoundException;
import models.*;
public class ControllerApp {
	private IOManager view;
	private Colombia model;
	
	public ControllerApp() {
		view = new IOManager();
		model = new Colombia();
		model.autogenerateDepartment();
		init();
	}
	
	public void init() {
		//		addMine();
		int option;
		do {
			option = view.selectOptionMenu();
			switch (option) {
			case 1:
				showTable();
				break;
			case 2: 
				addMine();
				break;
			case 3: 
				removeMine();
				break;
			default:
				view.showError(null);
				break;
			}
		} while (option != 4 );
	}
	
	public void showTable() {
		view.showTable(model.getListDepartment());
	}
	
	public void addMine() {
		try {
			model.createMine(view.readDepartment(), view.readNameMine(), view.readMeterMine(), view.readOreType(), view.readKilogram(), view.readId(), view.readMineType(), view.readBudgetMine());
		} catch (DepartmentNotFoundException e) {
			view.showError(e.toString());
		}
	}
	
	public void removeMine() {
		try {
			model.sendRemoveMine(view.readDepartment(), view.readId());
		} catch (MineNotFoundException e) {
			view.showError(e.getMessage());
		}
	}
}
