package controllers;
import views.IOManager;
import exceptions.*;
import models.*;
public class ControllerApp {
	private IOManager view;
	private Colombia model;
	
	public ControllerApp() {
		view = new IOManager();
		model = new Colombia();
		model.autogenerateDepartment();
		init();
	}
	
	public void init() {
		//		addMine();
		try {
			int option;
			do {
				option = view.selectOptionMenu();
				switch (option) {
				case 1:
					showTable();
					break;
				case 2: 
					addMine();
					break;
				case 3: 
					removeMine();
					break;
				case 4: 
					editMine();
					break;
				case 5:
					realizeEconomy();
					break;
				case 6:
					selectReports();
					break;
				case 7:
					break;
				default:
					throw new OptionInvalidException();
				}
			} while (option != 7 );
		} catch(OptionInvalidException e) {
			view.showError(e.getMessage());
			init();
		} catch(NumberFormatException e2) {
			view.showError("Opcion Invalida");
			init();
		} catch (DepartmentNotFoundException e) {
			view.showError(e.getMessage());
			init();
		}
	}
	

	public void showTable() {
		view.showTable(model.getListDepartment());
	}
	
	public void addMine() {
		try {
			model.createMine(view.readDepartment(), view.readNameMine(), view.readMeterMine(), view.readOreType(), view.readKilogram(), view.readId(), view.readMineType(), view.readBudgetMine());
			view.showSucesfull();
		} catch (DepartmentNotFoundException | NumberFormatException e) {
			view.showError(e.getMessage());
		}
	}
	
	public void removeMine() {
		try {
			model.sendRemoveMine(view.readDepartment(), view.readId());
			view.showSucesfull();
		} catch (MineNotFoundException | NumberFormatException e) {
			view.showError(e.getMessage());
		}
	}
	
	public void editMine() throws OptionInvalidException {
		int option = view.selectOptionMenuEdit();
		switch (option) {
		case 1:
			editKilogramPrice();
			break;
		case 2:
			editOreType();
			break;
		case 3:
			break;
		default:
			throw new OptionInvalidException();
		}
	}
	
	public void editKilogramPrice() {
		try {
			model.editKilogramPriceMine(view.readDepartment(), view.readId(), view.readKilogram());
			view.showSucesfull();
		} catch (MineNotFoundException | DepartmentNotFoundException e) {
			view.showError(e.getMessage());
		}
		
	}
	
	public void editOreType() {
		try {
			DepartmentName department = view.readDepartment();
			int id = view.readId();
			MineType mineType = view.readMineType();
			OreType oreType = view.readOreType();
			model.editOreType(department,id,oreType);
			model.editMineType(department, id, mineType);
			view.showSucesfull();
		} catch (MineNotFoundException | DepartmentNotFoundException e) {
			view.showError(e.getMessage());
		}
	}
	
	private void realizeEconomy() {
		try {
			int option = view.readOptionEconomy();
			switch (option) {
			case 1:
				sellOre(view.readKilogram(), view.readDepartment(), view.readId());
				break;
			case 2:
				buyInsume(view.readMount(), view.readDepartment(), view.readId());
			case 3:
				break;
			default:
				throw new OptionInvalidException();
			}
		} catch (OptionInvalidException|NumberFormatException e) {
			view.showError(e.getMessage());
			realizeEconomy();
		}
	}
	
	private void sellOre(int kilos, DepartmentName department, int idMine) {
		try {
			model.sellOre(department, idMine, kilos);
			view.showSucesfull();
		} catch (MineNotFoundException | DepartmentNotFoundException e) {
			view.showError(e.getMessage());
		}
	}
	
	private void buyInsume(int mount, DepartmentName department, int idMine) {
		try {
			model.buyInsumes(department, idMine, mount);
			view.showSucesfull();
		} catch (MineNotFoundException | DepartmentNotFoundException e) {
			view.showError(e.getMessage());
		}
	}
	
	private void selectReports() throws OptionInvalidException, DepartmentNotFoundException {
		int option = view.showMenuGeneralReports();
		switch (option) {
		case 1:
			selectTypeReportQuantityMines();
			break;
		case 2:
			selectTypeReportGain();
			break;
		case 3:
			break;
		default:
			throw new OptionInvalidException();
		}
	}
	
	private void selectTypeReportQuantityMines() throws DepartmentNotFoundException, OptionInvalidException {
		int option = view.showMenuQuantityMines();
		switch (option) {
		case 1:
			createReportMinesPerDepartment();
			break;
		case 2:
			break;
		default:
			throw new OptionInvalidException();
		}
	}
	
	private void selectTypeReportGain() throws DepartmentNotFoundException, OptionInvalidException {
		int option = view.showMenuGains();
		switch (option) {
		case 1:
			createReportGainPerMine();
			break;
		case 2:
			break;
		case 3:
			break;
		default:
			throw new OptionInvalidException();
		}
	}
	
	private void createReportGainPerMine() throws DepartmentNotFoundException {
		view.showReportQuantityMines(model.generateReportGainsPerMine(view.readDepartment()));
	}
	
	private void createReportMinesPerDepartment() {
		view.showReportOne(model.generateReportMinesPerDepartment());
	}
}
