package models;

import javax.swing.*;

import org.jfree.chart.*;
import org.jfree.data.category.*;
import org.jfree.chart.plot.*;
import exceptions.DepartmentNotFoundException;
import exceptions.MineNotFoundException;

public class Colombia {
	private Department[] listDepartment;
	
	public Colombia() {
		listDepartment = new Department[10]; 
	}
	
	public void autogenerateDepartment() {
		listDepartment[0] = new Department(DepartmentName.BOYACA,250000);
		listDepartment[1] = new Department(DepartmentName.CUNDINAMARCA,250000);
		listDepartment[2] = new Department(DepartmentName.ANTIOQUIA,250000);
		listDepartment[3] = new Department(DepartmentName.TOLIMA,250000);
		listDepartment[4] = new Department(DepartmentName.SANTANDER,250000);
		listDepartment[5] = new Department(DepartmentName.NORTE_DE_SANTANDER,250000);
		listDepartment[6] = new Department(DepartmentName.CORDOBA,250000);
		listDepartment[7] = new Department(DepartmentName.CESAR,250000);
		listDepartment[8] = new Department(DepartmentName.LA_GUAJIRA,250000);
		listDepartment[9] = new Department(DepartmentName.CAUCA,250000);
	}
	
	public int searchDepartment(DepartmentName name) throws DepartmentNotFoundException {
		for (int i = 0; i < listDepartment.length; i++) {
			if(listDepartment[i].getName().equals(name.getName()))
				return i;
		}
		throw new DepartmentNotFoundException();
	}
	
	public void createMine(DepartmentName department, String nameMine,int meter, OreType oreType, int kilogramPrice, int id, MineType mineType,int budgetMine) throws DepartmentNotFoundException {
		listDepartment[searchDepartment(department)].addMine(new Mine(nameMine,meter,oreType, kilogramPrice,id,mineType,budgetMine));
	}
	
	public void sendRemoveMine(DepartmentName department, int id) throws MineNotFoundException {
		for (Department department2 : listDepartment) {
			if(department2.getName().equals(department.getName()))
				department2.removeMine(id);
		}
	}
	
	public Department[] getListDepartment() {
		return listDepartment;
	}
	
	public void modifyKilogramPriceMine(DepartmentName department, int id, int newKilogramPrice) throws MineNotFoundException, DepartmentNotFoundException {
		for (Department department2 : listDepartment) {
			if(department2.getName().equals(department.getName()))
				department2.searchMine(id).setKilogramPrice(newKilogramPrice);
		}
		throw new DepartmentNotFoundException();
	}
	public void graphicTest() {
		DefaultCategoryDataset data = new DefaultCategoryDataset();
		data.addValue(listDepartment[0].getListMine().size(), DepartmentName.BOYACA, "minas");
		data.addValue(listDepartment[1].getListMine().size(), DepartmentName.CUNDINAMARCA, "minas");
		data.addValue(listDepartment[2].getListMine().size(), DepartmentName.ANTIOQUIA, "minas");
		data.addValue(listDepartment[3].getListMine().size(), DepartmentName.TOLIMA, "minas");
		data.addValue(listDepartment[4].getListMine().size(), DepartmentName.SANTANDER, "minas");
		data.addValue(listDepartment[5].getListMine().size(), DepartmentName.NORTE_DE_SANTANDER, "minas");
		data.addValue(listDepartment[6].getListMine().size(), DepartmentName.CORDOBA, "minas");
		data.addValue(listDepartment[7].getListMine().size(), DepartmentName.CESAR, "minas");
		data.addValue(listDepartment[8].getListMine().size(), DepartmentName.LA_GUAJIRA, "minas");
		data.addValue(listDepartment[9].getListMine().size(), DepartmentName.CAUCA, "minas");


		JFreeChart graphic = ChartFactory.createBarChart3D("Minas", "#minas", "cantidad de minas", data, PlotOrientation.VERTICAL, true, true, false);
		ChartPanel control = new ChartPanel(graphic);
		JFrame  window  = new JFrame ("graficas minas ");
		window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		window.add(control);
		window.setSize(500, 600);
		window.setVisible(true);
		window.setLocationRelativeTo(null);
	}

}





